# Generated by Django 5.0.7 on 2024-07-16 21:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique user ID')),
                ('town', models.CharField(max_length=100, verbose_name='Last city requested by user')),
            ],
        ),
    ]
