# Generated by Django 5.0.7 on 2024-07-18 18:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='user',
            name='cookie_token',
            field=models.CharField(default='vnajnblg', editable=False, unique=True, verbose_name='Cookie key'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(default='ru', max_length=10, verbose_name='User locale'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique request ID')),
                ('town', models.CharField(max_length=100, verbose_name='City requested by user')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Request history',
                'verbose_name_plural': 'Request histories',
            },
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique forecast ID')),
                ('forecast', models.TextField(verbose_name='Weather forecast')),
                ('town', models.CharField(max_length=100, verbose_name='Town for which the forecast was requested')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Forecast creation date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Weather forecast',
                'verbose_name_plural': 'Weather forecasts',
            },
        ),
    ]
