# Generated by Django 5.0.7 on 2024-07-17 09:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Unique request ID')),
                ('town', models.CharField(max_length=100, verbose_name='City requested by user')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Request creation date')),
            ],
        ),
    ]
